### ISSUE TITLE
Bootstrap process fails for Amazon Linux 

### ISSUE THREAD

**Issue by ilumb** [UnivaCorporation/tortuga#135]
There seem to be some Puppet and/or Python dependencies that are too restrictive to account for Linux variants _other_ than CentOS during the bootstrap process ... I am interested in making use of Amazon Linux in AWS. Can you please address this? 

-Ian

**Comment by EmmEff** [comment]
See issue: https://github.com/UnivaCorporation/tortuga-kit-awsadapter/issues/58
