### ISSUE TITLE
Improve how provisioning networks are associated with hardware profiles

### ISSUE THREAD

**Issue by dtougas** [UnivaCorporation/tortuga#40]
The mechanism for associating provisioning networks to hardware profiles is confusing. Here is an example...

I can add a provisioning NIC using the following command:

`add-nic --nic=eth1`

And I can verify it is installed with the following:

`get-provisioning-nics`

Which will return:

`[eth1]`

And if I type:

`get-provisioning-networks`

I see the following:

`- {netmask: 255.255.255.0, network: 192.168.20.0}`

However, if I try to associate it with a hardware profile like this:

`update-hardware-profile --name PROFILE_NAME --add-provisioning-nic=eth1`

I get the following error message:

`Node with IP address [eth1] not found.`

The reason that this error happens is because the current correct way is actually to do the following:

`update-hardware-profile --name PROFILE_NAME --add-provisioning-nic=192.168.20.10 --add-network=192.168.20.0/255.255.255.0/eth0`

Where `eth0` is the name of the NIC on the node that will be provisioned through this hardware profile.

I think that the UX for this process could be refactored to make the process clearer and more consistent for admins.

**Comment by EmmEff** [comment]
The interface `eth1` in the argument `--add-network xxx/yyy/eth1` should probably be `eth0`. This is the device name on the compute node itself, meaning that `eth0` on the compute node will be connected to the provisioning network.

**Comment by dtougas** [comment]
OK, fixed my original submission.
