### ISSUE TITLE
The is_requirements_empty uses wrong read method

### ISSUE THREAD

**Issue by cameronbrunner** [UnivaCorporation/tortuga#517]
The is_requirements_empty method in kit/utils.py uses readline() instead of readlines() (I think that is what was intended).  This causes any requirements file with a comment on the first line to be detected as empty,

@dtougas

**Comment by dtougas** [comment]
Fixed here: https://github.com/UnivaCorporation/tortuga/commit/63234efb6ff30dac1239ae45d7fbd9dc4e91b8c6
