### ISSUE TITLE
Tortuga installer does not support Amazon Linux

### ISSUE THREAD

**Issue by tpdownes** [UnivaCorporation/tortuga#524]
Planting this as a placeholder.

Tortuga installer detects OS family and release by looking for the existence of specific packages which vary from RHEL to its derivatives.

Main issue is that "Amazon Linux 2" is like "RHEL 7" and so, even adding `system-release` as the package to query, one gets a nonsense answer for which release of EPEL to install.

I might consider re-thinking the package-based approach in favor of testing for `/etc/os-release` and reading the variables from there. `ID_LIKE` directly tells you if it's a RHEL-flavor. I believe `os-release` is a SystemD-ism so the old approach (or something like it) would have to be maintained for RHEL6 and derivatives.

Amazon Linux 1 doesn't matter to my knowledge. I don't want to invest more time in this right now since I don't have a customer that actually uses Amazon Linux 1 or 2. I was using it in testing.

**Comment by cameronbrunner** [comment]
I think its really just the puppet modules and some package repositories (amazon has some custom ones) that makes it any bit different.  Are you thinking we will have more issues than this?

**Comment by tpdownes** [comment]
I was describing the manner in which`install-tortuga.sh` detects OS family and name (in facter-speak).  Assuming that can be made to work, I do believe Amazon Linux 2 and RHEL7 are in most respects equivalent for 3rd-party repos.

I'm not sure how much supporting Amazon Linux matters, so mostly I'm documenting the problem if it ever becomes one.
