### ISSUE TITLE
Cannot import profile from JSON if it does not already exist

### ISSUE THREAD

**Issue by tpdownes** [UnivaCorporation/tortuga#528]
This [line](https://github.com/UnivaCorporation/tortuga/blob/4858db5ad384c47e91601c1a1d7d1068b6c7d02b/src/core/src/tortuga/scripts/adapter_mgmt.py#L535) will cause an exception when one attempts to import a profile that does not yet exist.
```
$ adapter-mgmt import -r AWS --json-file /opt/tortuga/etc/cloud-connector-stat-mod-aor.json
local variable 'profile_exists' referenced before assignment
```
Subsequent lines need to be changed to behave according to the implications of `profile_exists`.

These related issues are resolved by PR #527.

**Comment by cameronbrunner** [comment]
Fixed with PR #527
