### ISSUE TITLE
ResourceAdapter class doesn't respect user-defined installer IP address

### ISSUE THREAD

**Issue by tprestegard** [UnivaCorporation/tortuga#585]
The [`get_initial_tags` method](https://github.com/UnivaCorporation/tortuga/blob/master/src/installer/src/tortuga/resourceAdapter/resourceAdapter.py#L409-L444) is defined on the base `ResourceAdapter` class in tortuga to generate tags which document the software profile, hardware profile, installer IP, and installer hostname.

The AWS adapter kit provides an [`installer_ip` setting](https://github.com/UnivaCorporation/tortuga/blob/master/src/installer/src/tortuga/resourceAdapter/resourceAdapter.py#L409-L444) which is used to override the automatically-detected installer IP address.  However, `get_initial_tags` has no awareness of this parameter and just uses the automatically-detected IP address.

**Comment by tprestegard** [comment]
I can think of two ways to fix it:
1. Add an optional kwarg to `get_initial_tags` for passing the user-specified IP address and update the places where it is called in the AWS adapter subclass
2. Redefine `get_initial_tags` on the AWS adapter subclass and use the `installer_ip` setting if it is defined.

I lean towards #2 - @dtougas, do you have a preference?

**Comment by dtougas** [comment]
I think that the second option is the correct approach. You could override the method, call the super version of the method, then override any tags you like.

**Comment by tprestegard** [comment]
Sounds good - closing this issue and opening a [pull request](https://github.com/UnivaCorporation/tortuga-kit-awsadapter/pull/194) in the AWS adapter kit repo.
