### ISSUE TITLE
SCL repo should not be installed for CentOS 7.7 or 8.x

### ISSUE THREAD

**Issue by tpdownes** [UnivaCorporation/tortuga#624]
The Software Collections repo is enabled on CentOS 7.7 even though it is unused.

https://github.com/UnivaCorporation/tortuga/blob/a96cda8e34994e2b52aaceed2dc2442665ed29f7/src/install-script/install-tortuga.sh#L783-L791

In CentOS 8.x, the Software Collections repo is not avilable:
```
[tdownes@test ~]$ sudo -i yum install -y centos-release-scl
CentOS-8 - AppStream                                                                                                5.8 MB/s | 6.6 MB     00:01
CentOS-8 - Base                                                                                                     5.9 MB/s | 5.0 MB     00:00
CentOS-8 - Extras                                                                                                   9.7 kB/s | 4.8 kB     00:00
CentOS-8 - PowerTools                                                                                               1.7 MB/s | 2.0 MB     00:01
Google Compute Engine                                                                                               8.8 kB/s | 6.2 kB     00:00
Google Cloud SDK                                                                                                     22 MB/s |  33 MB     00:01
No match for argument: centos-release-scl
Error: Unable to find a match: centos-release-scl
```

There are a few other places in the installation script where it is assumed that SCL is installed on both CentOS and RHEL itself.

For RHEL, is it considered a step outside of the installer script [to enable the SCL repo](https://access.redhat.com/discussions/3677111)?

**Comment by dtougas** [comment]
IIRC, we had used the SCL to install Python 3 in the past, which is why I think we added it in the first place. TBH, I have not spent much time in the installer code, so I don't really have a clear picture on what all goes on in there from a big-picture perspective.

**Comment by tpdownes** [comment]
Yes. `centos-release-scl` is only necessary for CentOS 7.6 and below. All the paths with `/opt/rh` in them will only exist if this repo is installed.

On RHEL 7.6 and below, `centos-release-scl` is replaced by the subscription manager command in the link.

On both RHEL and CentOS 7.7,  neither of these steps are necessary and should be eliminated. All references to `/opt/rh` should only come into play if on 7.6 or below.

Or affirmatively drop support for 7.6 and below. A reasonable choice given that CentOS 7.6 is not supported by any mechanism and RHEL 7.6 is only supported with a 2nd license on top of the RHEL license.
