### ISSUE TITLE
Install script code imposes its own notion of correct pip version

### ISSUE THREAD

**Issue by tpdownes** [UnivaCorporation/tortuga#638]
It should be noted that [the install script code](https://github.com/UnivaCorporation/tortuga/blob/e50deb23d2e73291cc91f177dc2ce61cafd34405/src/install-script/install-tortuga.sh#L889-L891) is fundamentally at odds with [the Puppet code](https://github.com/UnivaCorporation/tortuga/blob/e50deb23d2e73291cc91f177dc2ce61cafd34405/src/kits/kit-base/tortuga_kits/base/puppet_modules/tortuga_kit_base/manifests/core/install.pp#L174-L182) which each attempt to enforce their own separate notions of the correct pip version.

Like the Highlander, there can be only one. Analysis:

1. Puppet is designed to enforce things like versions of packages while bash is not.
2. The installer script is only used in certain scenarios while `tortuga_kit_base::core` is used _all over the place_.

I argue that, by failing to treat the Puppet code as the source of truth on Puppet version, we have created the circumstances for issues like #636 and for `tortuga_kit_core::base` installations to have ancient `pip` clients.

Conclusion: I advise removing the version restrictions from the installer script in favor of ensuring the correct version is installed by Puppet. We will want to add code enforcing a minimum version of `setuptools` owing to the Azure client having a minimum dependency that is not documented in the package.

**Comment by dtougas** [comment]
The installer does have minimum version requirements for pip, that if not met can cause the installation to fail. I don't consider this to be enforcing anything other than ensuring it has what it needs to bootstrap the install.

I don't mind that the install makes sure it has what it needs to complete, then Puppet going ahead and changing things afterwards.

**Comment by tpdownes** [comment]
I'll discuss on our private gitlab repo.
