### ISSUE TITLE
Missing build-kit command

### ISSUE THREAD

**Issue by thesystemninjaneer** [UnivaCorporation/tortuga#647]
I wanted to build tortuga from this open source repo and evaluate its integration with aws using the aws install kit.

I first ran the [build procedures](https://github.com/UnivaCorporation/tortuga#build-instructions) to produce the tortuga bz2 bundle. Then I ran all the Quick Start install and build procedures from https://github.com/UnivaCorporation/tortuga/blob/master/doc/tortuga-7-admin-guide.md#manual-quickstart-installation for the master branch in this repo and saw the success messages after running `install-tortuga.sh` & `tortuga-setup.sh` scripts (`Tortuga successfully installed` & `Tortuga installation completed successfully!`)
```
# ls ${TORTUGA_ROOT}/kits
kit-base-7.1.0-0  kit-base-7.1.0-0.tar.bz2
# get-kit-list
base-7.1.0-0
# get-component-list
base-7.1.0-0 core-7.1.0
base-7.1.0-0 dhcpd-7.1.0
base-7.1.0-0 dns-7.1.0
base-7.1.0-0 installer-7.1.0
base-7.1.0-0 pdsh-7.1.0
```
I then got to step 11 to install the aws kit but there is no `kit-awsadapter-*.tar.bz2` file (that step may need a note saying how that file is created). Since the kit bz2 didn't exist, I tried to build it from the repo needed cloned and built but the `build-kit` command is no where on the machine. I see the [aws kit doc](https://github.com/UnivaCorporation/tortuga-kit-awsadapter/blob/master/README.md#building-the-kit) says `build-kit` is supposed to be created by the core package but doesn't look like the tortuga install and setup scripts created it in my case.
```
# pwd
/root/tortuga-7.1.0+rev6197df8
# /opt/tortuga/bin/install-kit --i-accept-the-eula kit-awsadapter-*.tar.bz2      #<---from step 11 in admin guid
File [kit-awsadapter-*.tar.bz2] not found at URL [kit-awsadapter-*.tar.bz2]
#
# find / -name build-kit
#
# git clone https://github.com/UnivaCorporation/tortuga-kit-awsadapter && cd tortuga-kit-awsadapter
# python3 -m venv venv
# . venv/bin/activate
# pip install -r requirements.txt
...
# /opt/tortuga/bin/paver build
Build failed: Unknown task: build
```
Are there other instructions I need to follow to get the aws kit added to my tortuga install?

**Comment by thesystemninjaneer** [comment]
I was able to figure out adding the aws kit using the included Dockerfiles like this.
```
git clone https://github.com/UnivaCorporation/tortuga && cd tortuga
python3 -m venv venv
. venv/bin/activate
pip install -r requirements.txt
paver build
cd docker
tar xjf ../dist/tortuga-*.tar.bz2
docker build -t tortuga-build-kit:latest -f Dockerfile.build-kit .
git clone https://github.com/UnivaCorporation/tortuga-kit-awsadapter
docker run -v $PWD/tortuga-kit-awsadapter:/kit-src tortuga-build-kit:latest
install-kit tortuga-kit-awsadapter/dist/kit-awsadapter-7.1.1-0.tar.bz2
```
If I get some free time soon I'll submit a PR with recommended doc updates.

**Comment by cameronbrunner** [comment]
Thanks for the follow up!
